name: Test Doppler Secrets
on:
  workflow_dispatch: # lo puedes lanzar manualmente desde GitHub Actions

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mostrar secretos disponibles (no sensibles)
        run: |
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
          echo "Bucket: ${{ secrets.S3_BUCKET }}"
